import { useCallback, useRef, useState } from 'react';
import type {
  BloodReportAnalysis,
  UseBloodReportAnalysisOptions,
  UseBloodReportAnalysisReturn,
} from './blood-report-types';

// ─────────────────────────────────────────────────────────────────────────────
//  Constants
// ─────────────────────────────────────────────────────────────────────────────

const GROQ_CHAT_URL = 'https://api.groq.com/openai/v1/chat/completions';
const DEFAULT_MODEL = 'llama3-70b-8192';
const TIMEOUT_MS    = 30_000;

// ─────────────────────────────────────────────────────────────────────────────
//  System prompt — instructs model to return ONLY valid JSON
// ─────────────────────────────────────────────────────────────────────────────

const SYSTEM_PROMPT = `
You are Hemo-Edge AI, an expert haematology and clinical-pathology assistant
embedded inside a medical diagnostic application. Your sole job is to analyse
blood test reports provided by the user and return a structured JSON response.

OUTPUT RULES (non-negotiable):
1. Return ONLY a single valid JSON object — no markdown, no code fences, no
   prose before or after.
2. The JSON must exactly match this TypeScript interface:

{
  analysisId:          string,
  analyzedOn:          string,
  modelUsed:           string,
  markers: Array<{
    name:           string,
    value:          string,
    unit:           string,
    referenceRange: string,
    status:         "normal" | "low" | "high" | "borderline"
  }>,
  predictedConditions: Array<{
    condition:   string,
    likelihood:  "possible" | "probable" | "highly likely",
    explanation: string,
    icdCode?:    string
  }>,
  overallRisk:         "low" | "moderate" | "high" | "critical",
  summary:             string,
  recommendations:     string[],
  urgency:             "routine" | "soon" | "urgent" | "emergency",
  disclaimer:          string
}

3. Extract every blood marker you can identify from the report.
4. Predict conditions based on the combination of abnormal markers.
5. Set overallRisk / urgency conservatively — err on the side of caution.
6. recommendations should be ordered: most important first.
7. Always set disclaimer to:
   "This analysis is generated by an AI model for informational purposes only.
    It is not a substitute for professional medical advice, diagnosis, or treatment.
    Please consult a licensed haematologist or physician before making any health decisions."
8. If the input is not a recognisable blood report, return:
   markers=[], predictedConditions=[], overallRisk="low",
   summary="The provided text does not appear to be a blood report.",
   recommendations=["Please upload a valid blood test report."],
   urgency="routine".
`.trim();

// ─────────────────────────────────────────────────────────────────────────────
//  Helper — call Groq with timeout + detailed error messages
// ─────────────────────────────────────────────────────────────────────────────

async function callGroq(
  apiKey: string,
  model: string,
  reportText: string,
): Promise<BloodReportAnalysis> {

  // ── 1. Validate API key ───────────────────────────────────────────────────
  const trimmedKey = apiKey?.trim() ?? '';
  if (!trimmedKey) {
    throw new Error(
      'Groq API key is missing.\n\n' +
      'Fix: Add  EXPO_PUBLIC_GROQ_API_KEY=gsk_...  to your .env file, ' +
      'then stop and restart Expo (npx expo start --clear).',
    );
  }
  if (!trimmedKey.startsWith('gsk_')) {
    console.warn('HEMO-EDGE: API key does not start with "gsk_" — may be invalid.');
  }

  console.log(`HEMO-EDGE: -> Groq  model=${model}  key=${trimmedKey.slice(0, 10)}...`);

  // ── 2. Fetch with timeout ─────────────────────────────────────────────────
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), TIMEOUT_MS);

  let response: Response;
  try {
    response = await fetch(GROQ_CHAT_URL, {
      method: 'POST',
      signal: controller.signal,
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${trimmedKey}`,
      },
      body: JSON.stringify({
        model,
        temperature: 0.1,
        max_tokens: 2048,
        response_format: { type: 'json_object' },
        messages: [
          { role: 'system', content: SYSTEM_PROMPT },
          {
            role: 'user',
            content: `Analyse the following blood test report and return the JSON:\n\n${reportText}`,
          },
        ],
      }),
    });
  } catch (fetchErr: any) {
    clearTimeout(timer);
    if (fetchErr?.name === 'AbortError') {
      throw new Error(
        `Groq request timed out after ${TIMEOUT_MS / 1000}s.\n` +
        'Check your internet connection and try again.',
      );
    }
    throw new Error(
      `Network error reaching Groq: ${fetchErr?.message ?? String(fetchErr)}\n\n` +
      'Make sure the device has internet access.',
    );
  }
  clearTimeout(timer);

  // ── 3. Handle HTTP errors with clear messages ─────────────────────────────
  if (!response.ok) {
    const body = await response.text().catch(() => '');
    console.error('HEMO-EDGE: Groq HTTP', response.status, body.slice(0, 300));

    switch (response.status) {
      case 401:
        throw new Error(
          'Groq API key rejected (401 Unauthorized).\n' +
          'Check EXPO_PUBLIC_GROQ_API_KEY in your .env and restart Expo.',
        );
      case 429:
        throw new Error('Groq rate limit reached (429). Wait a moment and try again.');
      case 400:
        throw new Error(
          `Groq bad request (400): ${body.slice(0, 200)}\n` +
          'The model name may be wrong — default is "llama3-70b-8192".',
        );
      default:
        throw new Error(`Groq API error ${response.status}: ${body.slice(0, 200)}`);
    }
  }

  // ── 4. Parse response ─────────────────────────────────────────────────────
  const data = await response.json();
  const rawContent: string = data?.choices?.[0]?.message?.content ?? '';

  if (!rawContent) {
    throw new Error('Groq returned an empty response. Please try again.');
  }

  console.log('HEMO-EDGE: <- Groq raw response length:', rawContent.length);

  // Strip accidental markdown fences
  const cleaned = rawContent
    .replace(/^```(?:json)?\s*/i, '')
    .replace(/\s*```$/i, '')
    .trim();

  let parsed: BloodReportAnalysis;
  try {
    parsed = JSON.parse(cleaned) as BloodReportAnalysis;
  } catch {
    console.error('HEMO-EDGE: JSON parse failed. Raw preview:', cleaned.slice(0, 300));
    throw new Error(
      `Groq response was not valid JSON.\nPreview: ${cleaned.slice(0, 100)}`,
    );
  }

  // ── 5. Fill in any missing fields ────────────────────────────────────────
  parsed.analysisId          ??= `BA-${Math.floor(10000 + Math.random() * 90000)}`;
  parsed.analyzedOn          ??= new Date().toISOString();
  parsed.modelUsed           ??= model;
  parsed.markers             ??= [];
  parsed.predictedConditions ??= [];
  parsed.overallRisk         ??= 'low';
  parsed.summary             ??= '';
  parsed.recommendations     ??= [];
  parsed.urgency             ??= 'routine';
  parsed.disclaimer          ??=
    'This analysis is for informational purposes only. Consult a licensed physician.';

  return parsed;
}

// ─────────────────────────────────────────────────────────────────────────────
//  Hook
// ─────────────────────────────────────────────────────────────────────────────

/**
 * useBloodReportAnalysis
 *
 * Sends raw blood-report text (OCR output, pasted lab values, etc.) to Groq
 * and returns structured disease predictions + actionable recommendations.
 *
 * @example
 * const { analyzeReport, isAnalyzing, result, error } = useBloodReportAnalysis({
 *   groqApiKey: process.env.EXPO_PUBLIC_GROQ_API_KEY ?? '',
 * });
 * await analyzeReport(ocrText);
 */
export function useBloodReportAnalysis(
  options: UseBloodReportAnalysisOptions,
): UseBloodReportAnalysisReturn {
  const { groqApiKey, model = DEFAULT_MODEL } = options;

  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [result,      setResult]      = useState<BloodReportAnalysis | null>(null);
  const [error,       setError]       = useState<string | null>(null);

  const mountedRef = useRef(true);
  mountedRef.current = true;

  const analyzeReport = useCallback(
    async (reportText: string): Promise<BloodReportAnalysis> => {
      if (!reportText?.trim()) {
        const msg = 'No report text provided.';
        setError(msg);
        throw new Error(msg);
      }

      setIsAnalyzing(true);
      setError(null);

      try {
        const analysis = await callGroq(groqApiKey, model, reportText);

        if (mountedRef.current) setResult(analysis);

        console.log(
          `HEMO-EDGE: Analysis done. risk=${analysis.overallRisk} ` +
          `conditions=${analysis.predictedConditions.length} ` +
          `markers=${analysis.markers.length}`,
        );
        return analysis;
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        console.error('HEMO-EDGE: analyzeReport failed ->', msg);
        if (mountedRef.current) setError(msg);
        throw err;
      } finally {
        if (mountedRef.current) setIsAnalyzing(false);
      }
    },
    [groqApiKey, model],
  );

  const reset = useCallback(() => {
    setResult(null);
    setError(null);
    setIsAnalyzing(false);
  }, []);

  return { analyzeReport, isAnalyzing, result, error, reset };
}
